### ISSUE TITLE
Pixellated / blurry animation

### ISSUE THREAD

**Issue by LeoSeyers** [LottieFiles/lottie-player#163]
Hello,

I'm currently implementing an animation as a full bleed cover on a landing section but it does not appear as sharp as expected on larger screen and 4K resolution. When zoomed in with user preference, it appears pixellated.

It's hard to tell from the preview if since I cannot zoom past 200%. Original sequence is 1920x1080 and is all vector shapes I believe.

Preview sharing : https://lottiefiles.com/share/fsqkvjhw
Staging : https://sibelga-ra-2021.stoemp-dev.com/fr/

Code implementartion is basic :

``` html
 <lottie-player autoplay loop mode='normal' speed='1' src='/public/animation-r2.json''></lottie-player>
```

``` js
 import '@lottiefiles/lottie-player'
```

``` css
     lottie-player {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
    }
```

Is there something that I've missed?

Best
Leo
