### ISSUE TITLE
Feature request: add ability fade controls in/out

### ISSUE THREAD

**Issue by tzbarkan** [LottieFiles/lottie-player#235]
With any version of lottie-player we have used up to the current 2.0.2, controls are either on or off. 

We would like to fade the controls in on `:hover`, `:focus`, and `:focus-within` and then back out.

Currently, the only way we see to do this without pushing code into the shadow dom is to define the control colors as transparent, and then change them on hover and focus:
```scss
lottie-player {
    --lottie-opacity-transition-speed: 200ms;
    --lottie-player-seeker-track-color: transparent;
    --lottie-player-toolbar-icon-active-color: transparent;
    --lottie-player-toolbar-icon-color: transparent;
    --lottie-player-toolbar-icon-hover-color: transparent;
    --lottie-player-seeker-thumb-color: transparent;

    background: transparent;

    &:hover, &:focus-within {
        --lottie-player-seeker-track-color: #ccc;
        --lottie-player-toolbar-icon-active-color: blue;
        --lottie-player-toolbar-icon-color: red;
        --lottie-player-toolbar-icon-hover-color: green;
        --lottie-player-seeker-thumb-color: orange;
    }
}
```

But this is suboptimal because it just goes from visible to invisible. Doing it this way is difficult to make into a smooth transition cross-browser, requiring keyframe animations based on @property defining the variable as a color.

So, we have been pushing a simple hover transition from opacity 0 to 1 and back via JS. But it would be nice not to hack at your code to do this smoothly.
